### ISSUE TITLE
second 123

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB1#105]
second 123

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xf89d5ab9d9dd3404966b9469a000af1cee9d051f8ba94c8fdaf502d22d4a59be](https://ropsten.etherscan.io/tx/0xf89d5ab9d9dd3404966b9469a000af1cee9d051f8ba94c8fdaf502d22d4a59be)
